name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: bash scripts/install.sh
      - run: npm ci
        working-directory: frontend
      - run: npm test --if-present
        working-directory: frontend
      - run: npm audit --audit-level=high
        working-directory: frontend
      - run: go vet ./...
      - run: go test -race ./...
      - run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - run: gosec ./...
      - run: wails build -platform windows/amd64
      - run: wails build -platform darwin/universal
      - run: wails build -platform linux/amd64
      - run: scripts/sign.sh build/bin/*
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}

